# Remarques :
2. branching on node / edge ? node (sub problem)
4. first column : artificial

# To do :
1. bornes dans colonnes génération (ok) et B&Price

In [1]:
using JuMP 
using Gurobi
using DelimitedFiles
using NBInclude
using LightGraphs
using MetaGraphs
const GUROBI_ENV = Gurobi.Env()
const ϵ = 0.00001;

Academic license - for non-commercial use only - expires 2021-06-25


In [2]:
@nbinclude("typedef.ipynb")
@nbinclude("data.ipynb")
@nbinclude("MIP.ipynb")
@nbinclude("master.ipynb")
@nbinclude("subproblem.ipynb")
@nbinclude("branch_and_price.ipynb")
@nbinclude("node.ipynb");

# I - Read data

In [6]:
data_folder = string(@__DIR__,"/../data")
instance = "MD-00001-00000010"
wmd_file = joinpath(data_folder, join([instance, ".wmd"]))
dat_file = joinpath(data_folder, join([instance, ".dat"]))
global pool = kep_pool(wmd_file, dat_file)
global weight = [get_prop(pool, arc, :weight) for arc in edges(pool)]
global e = collect(edges(pool))
global L = 2;

# II - Solve by MIP
Implement and solve an integer programming model for KEP: (**formualtion to change**)
\begin{align*}
\min\;\;\; &\sum_{i\in N}\sum_{j\in M} p_{ij} x_{ij}\\
\mbox{s.t.}\;\;\; 	&\sum_{j\in M} x_{ij}=1 &\forall i\in N\\
&\sum_{i\in N} t_{ij}x_{ij} \leq t^{\rm max}_{j} &\forall j\in M\\
&x\in \{0,1\}^{N\times M}.
\end{align*}


In [7]:
result = @timed solve_MIP(pool,L)

Academic license - for non-commercial use only - expires 2021-06-25
Gurobi Optimizer version 9.1.1 build v9.1.1rc0 (win64)
Thread count: 4 physical cores, 8 logical processors, using up to 8 threads
Optimize a model with 16 rows, 7 columns and 14 nonzeros
Model fingerprint: 0xaab731b1
Variable types: 0 continuous, 7 integer (7 binary)
Coefficient statistics:
  Matrix range     [1e+00, 1e+00]
  Objective range  [2e+00, 2e+00]
  Bounds range     [0e+00, 0e+00]
  RHS range        [1e+00, 1e+00]
Found heuristic solution: objective 4.0000000
Presolve removed 16 rows and 7 columns
Presolve time: 0.01s
Presolve: All rows and columns removed

Explored 0 nodes (0 simplex iterations) in 0.01 seconds
Thread count was 1 (of 8 available processors)

Solution count 1: 4 

Optimal solution found (tolerance 1.00e-04)
Best objective 4.000000000000e+00, best bound 4.000000000000e+00, gap 0.0000%

User-callback calls 34, time in user-callback 0.00 sec


(value = (4.0, [1.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0]), time = 0.004740999, bytes = 160656, gctime = 0.0, gcstats = Base.GC_Diff(160656, 0, 0, 2450, 0, 0, 0, 0, 0))

# III - B&Price

In [8]:
result = @timed solve_BP()

Current list of nodes to be processed:[1]
 Processing node 1 
Variables set to zero are:Tuple[]
Variables set to one are:Tuple[]
 Feasible solution with value 1.0 found 
 Pattern with items [14, 15] added 
 Feasible solution with value 3.0 found 
 Pattern with items [14, 15] added 
 Feasible solution with value 3.0 found 
 Pattern with items [14, 15] added 
 Feasible solution with value 3.0 found 
 Pattern with items [14, 15] added 
 Feasible solution with value 3.0 found 
 Pattern with items [14, 15] added 
 Feasible solution with value 3.0 found 
 Pattern with items [14, 15] added 
 Feasible solution with value 3.0 found 
 Pattern with items [14, 15] added 
 Feasible solution with value 3.0 found 
 Pattern with items [14, 15] added 
 Feasible solution with value 3.0 found 
 Pattern with items [14, 15] added 
 Feasible solution with value 3.0 found 
 Pattern with items [14, 15] added 
 Feasible solution with value 3.0 found 
 Pattern with items [14, 15] added 
 Feasible solution with 

 Pattern with items [14, 15] added 
 Feasible solution with value 3.0 found 
 Pattern with items [14, 15] added 
 Feasible solution with value 3.0 found 
 Pattern with items [14, 15] added 
 Feasible solution with value 3.0 found 
 Pattern with items [14, 15] added 
 Feasible solution with value 3.0 found 
 Pattern with items [14, 15] added 
 Feasible solution with value 3.0 found 
 Pattern with items [14, 15] added 
 Feasible solution with value 3.0 found 
 Pattern with items [14, 15] added 
 Feasible solution with value 3.0 found 
 Pattern with items [14, 15] added 
 Feasible solution with value 3.0 found 
 Pattern with items [14, 15] added 
 Feasible solution with value 3.0 found 
 Pattern with items [14, 15] added 
 Feasible solution with value 3.0 found 
 Pattern with items [14, 15] added 
 Feasible solution with value 3.0 found 
 Pattern with items [14, 15] added 
 Feasible solution with value 3.0 found 
 Pattern with items [14, 15] added 
 Feasible solution with value 3.0 found 

 Pattern with items [14, 15] added 
 Feasible solution with value 3.0 found 
 Pattern with items [14, 15] added 
 Feasible solution with value 3.0 found 
 Pattern with items [14, 15] added 
 Feasible solution with value 3.0 found 
 Pattern with items [14, 15] added 
 Feasible solution with value 3.0 found 
 Pattern with items [14, 15] added 
 Feasible solution with value 3.0 found 
 Pattern with items [14, 15] added 
 Feasible solution with value 3.0 found 
 Pattern with items [14, 15] added 
 Feasible solution with value 3.0 found 
 Pattern with items [14, 15] added 
 Feasible solution with value 3.0 found 
 Pattern with items [14, 15] added 
 Feasible solution with value 3.0 found 
 Pattern with items [14, 15] added 
 Feasible solution with value 3.0 found 
 Pattern with items [14, 15] added 
 Feasible solution with value 3.0 found 
 Pattern with items [14, 15] added 
 Feasible solution with value 3.0 found 
 Pattern with items [14, 15] added 
 Feasible solution with value 3.0 found 

 Feasible solution with value 3.0 found 
 Pattern with items [14, 15] added 
 Feasible solution with value 3.0 found 
 Pattern with items [14, 15] added 
 Feasible solution with value 3.0 found 
 Pattern with items [14, 15] added 
 Feasible solution with value 3.0 found 
 Pattern with items [14, 15] added 
 Feasible solution with value 3.0 found 
 Pattern with items [14, 15] added 
 Feasible solution with value 3.0 found 
 Pattern with items [14, 15] added 
 Feasible solution with value 3.0 found 
 Pattern with items [14, 15] added 
 Feasible solution with value 3.0 found 
 Pattern with items [14, 15] added 
 Feasible solution with value 3.0 found 
 Pattern with items [14, 15] added 
 Feasible solution with value 3.0 found 
 Pattern with items [14, 15] added 
 Feasible solution with value 3.0 found 
 Pattern with items [14, 15] added 
 Feasible solution with value 3.0 found 
 Pattern with items [14, 15] added 
 Feasible solution with value 3.0 found 
 Pattern with items [14, 15] added 

 Pattern with items [14, 15] added 
 Feasible solution with value 3.0 found 
 Pattern with items [14, 15] added 
 Feasible solution with value 3.0 found 
 Pattern with items [14, 15] added 
 Feasible solution with value 3.0 found 
 Pattern with items [14, 15] added 
 Feasible solution with value 3.0 found 
 Pattern with items [14, 15] added 
 Feasible solution with value 3.0 found 
 Pattern with items [14, 15] added 
 Feasible solution with value 3.0 found 
 Pattern with items [14, 15] added 
 Feasible solution with value 3.0 found 
 Pattern with items [14, 15] added 
 Feasible solution with value 3.0 found 
 Pattern with items [14, 15] added 
 Feasible solution with value 3.0 found 
 Pattern with items [14, 15] added 
 Feasible solution with value 3.0 found 
 Pattern with items [14, 15] added 
 Feasible solution with value 3.0 found 
 Pattern with items [14, 15] added 
 Feasible solution with value 3.0 found 
 Pattern with items [14, 15] added 
 Feasible solution with value 3.0 found 

 Feasible solution with value 3.0 found 
 Pattern with items [14, 15] added 
 Feasible solution with value 3.0 found 
 Pattern with items [14, 15] added 
 Feasible solution with value 3.0 found 
 Pattern with items [14, 15] added 
 Feasible solution with value 3.0 found 
 Pattern with items [14, 15] added 
 Feasible solution with value 3.0 found 
 Pattern with items [14, 15] added 
 Feasible solution with value 3.0 found 
 Pattern with items [14, 15] added 
 Feasible solution with value 3.0 found 
 Pattern with items [14, 15] added 
 Feasible solution with value 3.0 found 
 Pattern with items [14, 15] added 
 Feasible solution with value 3.0 found 
 Pattern with items [14, 15] added 
 Feasible solution with value 3.0 found 
 Pattern with items [14, 15] added 
 Feasible solution with value 3.0 found 
 Pattern with items [14, 15] added 
 Feasible solution with value 3.0 found 
 Pattern with items [14, 15] added 
 Feasible solution with value 3.0 found 
 Pattern with items [14, 15] added 

 Feasible solution with value 3.0 found 
 Pattern with items [14, 15] added 
 Feasible solution with value 3.0 found 
 Pattern with items [14, 15] added 
 Feasible solution with value 3.0 found 
 Pattern with items [14, 15] added 
 Feasible solution with value 3.0 found 
 Pattern with items [14, 15] added 
 Feasible solution with value 3.0 found 
 Pattern with items [14, 15] added 
 Feasible solution with value 3.0 found 
 Pattern with items [14, 15] added 
 Feasible solution with value 3.0 found 
 Pattern with items [14, 15] added 
 Feasible solution with value 3.0 found 
 Pattern with items [14, 15] added 
 Feasible solution with value 3.0 found 
 Pattern with items [14, 15] added 
 Feasible solution with value 3.0 found 
 Pattern with items [14, 15] added 
 Feasible solution with value 3.0 found 
 Pattern with items [14, 15] added 
 Feasible solution with value 3.0 found 
 Pattern with items [14, 15] added 
 Feasible solution with value 3.0 found 
 Pattern with items [14, 15] added 

 Pattern with items [14, 15] added 
 Feasible solution with value 3.0 found 
 Pattern with items [14, 15] added 
 Feasible solution with value 3.0 found 
 Pattern with items [14, 15] added 
 Feasible solution with value 3.0 found 
 Pattern with items [14, 15] added 
 Feasible solution with value 3.0 found 
 Pattern with items [14, 15] added 
 Feasible solution with value 3.0 found 
 Pattern with items [14, 15] added 
 Feasible solution with value 3.0 found 
 Pattern with items [14, 15] added 
 Feasible solution with value 3.0 found 
 Pattern with items [14, 15] added 
 Feasible solution with value 3.0 found 
 Pattern with items [14, 15] added 
 Feasible solution with value 3.0 found 
 Pattern with items [14, 15] added 
 Feasible solution with value 3.0 found 
 Pattern with items [14, 15] added 
 Feasible solution with value 3.0 found 
 Pattern with items [14, 15] added 
 Feasible solution with value 3.0 found 
 Pattern with items [14, 15] added 
 Feasible solution with value 3.0 found 

LoadError: InterruptException:

# Brouillon pour débeuger

14 15 ajoutés +s fois ? Pb de code / article 1 section 5.2.3  
solution entière pour RLP?  
UB = 2?

In [127]:
calculate_ysol(solution,node_pool)

16-element Array{Float64,1}:
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 2.0
 2.0
 1.0

In [128]:
solution

3-element Array{Any,1}:
 1.0
 0.0
 1.0

In [129]:
node_pool

3-element Array{Array{Int64,1},1}:
 [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
 [2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0]

In [101]:
global column_pool = Array{Array{Int,1},1}()
# this is a 2-dimensional array
# column_pool[i] is a pattern  (1-dimensional array = vector)
# pattern vectors are  such that:
#   -the first element is the objective value contribution
#   -the second to n+1 st elements are 1 or 0 depending on whether nth pair is included in the pattern or not


push!(column_pool,vcat(1,ones(Int,nv(pool)))) # push an artificial pattern 
push!(column_pool,zeros(Int,nv(pool)+1))    # push an empty pattern 


# set the global lower and upper bound to +,- infinity
global UB = Inf  # If we have a heuristic solution its value can be used   
global LB = -Inf # If we have an initial relaxation bound it can be used 

global Queue = Vector{Int}() # the Queue of nodes to process is an array of integers
global tree = Vector{TreeNode}() # the branch and price tree is an array of TreeNode objects

# the branch and price tree is initialized with the root node
# the root node is its own parent, it has no children (at the moment), its LB is -infinity, 
# there are no variables set to 0 or 1 at the root node
push!(tree,TreeNode(0,[],Inf,[],[]))   
push!(Queue,1)  # the indices of nodes to be processed are pushed to the Queue


1-element Array{Int64,1}:
 1

In [102]:
current = Queue[end]

1

## génération de colonne

In [103]:

global nodestobedeleted = []
    
# Calculate columns that are compatible with the branching constraints
# Function calculate_columns TO COMPLETE (see above)
node_pool = calculate_columns(1)

2-element Array{Array{Int64,1},1}:
 [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

In [104]:
choosecerc,z,mastermodel = node_master(node_pool)

(ConstraintRef{Model,MathOptInterface.ConstraintIndex{MathOptInterface.ScalarAffineFunction{Float64},MathOptInterface.LessThan{Float64}},ScalarShape}[choosecerc[1] : z_1 <= 1.0, choosecerc[2] : 0 <= 1.0, choosecerc[3] : 0 <= 1.0, choosecerc[4] : 0 <= 1.0, choosecerc[5] : 0 <= 1.0, choosecerc[6] : 0 <= 1.0, choosecerc[7] : 0 <= 1.0, choosecerc[8] : 0 <= 1.0, choosecerc[9] : 0 <= 1.0, choosecerc[10] : 0 <= 1.0, choosecerc[11] : 0 <= 1.0, choosecerc[12] : 0 <= 1.0, choosecerc[13] : 0 <= 1.0, choosecerc[14] : 0 <= 1.0, choosecerc[15] : 0 <= 1.0, choosecerc[16] : 0 <= 1.0], VariableRef[z_1, z_2], A JuMP Model
Maximization problem with:
Variables: 2
Objective function type: GenericAffExpr{Float64,VariableRef}
`GenericAffExpr{Float64,VariableRef}`-in-`MathOptInterface.LessThan{Float64}`: 16 constraints
`VariableRef`-in-`MathOptInterface.GreaterThan{Float64}`: 2 constraints
`VariableRef`-in-`MathOptInterface.LessThan{Float64}`: 2 constraints
Model mode: AUTOMATIC
CachingOptimizer state: EMPTY_

In [145]:
optimize!(mastermodel)

In [146]:
π = JuMP.dual.(choosecerc)

16-element Array{Float64,1}:
 -0.0
 -0.0
 -0.0
 -0.0
 -0.0
 -0.0
 -0.0
 -0.0
 -0.0
 -0.0
 -0.0
 -0.0
 -0.0
 -2.0
 -0.0
 -0.0

In [147]:
value = JuMP.objective_value(mastermodel)

3.0

In [148]:
solution=[]
for m in 1:length(z)
    push!(solution,JuMP.value.(z[m]))
end
solflat = collect(Iterators.flatten(solution))

4-element Array{Float64,1}:
 1.0
 0.0
 0.0
 1.0

In [149]:
nodeub = sum(π[i] for i in 1:nv(pool))
nodelb = value

3.0

In [150]:
maxobj = 0


0

In [151]:
SPobj,column,x = kep_subproblem(π,1)

(4.0, [0.0, 0.0, 0.0, 0.0, 0.0, -0.0, 0.0, 0.0, -0.0, 0.0, 0.0, 0.0, -0.0, 1.0, 1.0, 0.0], [0.0, 0.0, 0.0, 0.0, 0.0, -0.0, -0.0, -0.0, -0.0, 0.0  …  -0.0, -0.0, 0.0, -0.0, -0.0, 1.0, 0.0, 0.0, 1.0, 0.0])

In [152]:
rc = SPobj

4.0

In [153]:
if rc>=maxobj maxobj=rc end

4.0

In [154]:
column_cost = sum(weight .* x)

2.0

In [155]:
push!(column_pool,vcat(column_cost,column))
# Store column in the node pool
push!(node_pool,vcat(column_cost,column))


5-element Array{Array{Int64,1},1}:
 [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
 [2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0]
 [2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0]
 [2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0]

In [156]:
push!(z,@variable(mastermodel,lower_bound=0,upper_bound=1))

5-element Array{VariableRef,1}:
 z_1
 z_2
 z_3
 z_4102
 noname

In [139]:
set_name(z[end], "z_$(length(column_pool))")

In [140]:
for j in 1:nv(pool)
    set_normalized_coefficient(choosecerc[j], z[end], column[j])            
end

In [141]:
set_objective_function(mastermodel, objective_function(mastermodel) + column_cost*z[end])

In [142]:
nodeub += SPobj

2.0

In [143]:
if nodeub<=tree[1].ub tree[1].ub = nodeub end

2.0

In [144]:
2*abs((tree[1].ub-nodelb))/abs((nodelb+tree[1].ub))<ϵ || maxobj<=0

false